# inherit_from: .rubocop_todo.yml

Layout/LineLength:
  Max: 120
  
Style/Documentation: 
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

AllCops:
  Exclude:
    - 'bin/bundle'

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'