
default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV["DATABASE_HOSTNAME"] %>
  port: <%= ENV["DATABASE_PORT"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rest_api_clothes_development

test:
  <<: *default
  database: rest_api_clothes_test